/*Apaga os relacionamentos*/
ALTER TABLE LABDATABASE.MARCACOES DROP CONSTRAINT FUNCIONARIOS_MARCACOES_FK;

/*Apaga as tabelas*/
DROP TABLE LABDATABASE.FUNCIONARIOS;
DROP TABLE LABDATABASE.MARCACOES;

/*Apaga as sequences*/
DROP SEQUENCE LABDATABASE.MARCACOES_CODIGO_MARCACAO_SEQ;
DROP SEQUENCE LABDATABASE.FUNCIONARIOS_CODIGO_FUNCIONARIO_SEQ;

/*Cria as tabelas*/
CREATE TABLE LABDATABASE.FUNCIONARIOS (
                CODIGO_FUNCIONARIO NUMBER NOT NULL,
                NOME VARCHAR2(255) NOT NULL,
                CPF VARCHAR2(20) NOT NULL,
                CARGO VARCHAR2(255) NOT NULL,
                CONSTRAINT FUNCIONARIOS_PK PRIMARY KEY (CODIGO_FUNCIONARIO)
);

CREATE TABLE LABDATABASE.MARCACOES (
                CODIGO_MARCACAO NUMBER NOT NULL,
                DATA_MARCACAO DATE NOT NULL,
                HORA_ENTRADA DATE NOT NULL,
                HORA_SAIDA DATE NULL,
                CODIGO_FUNCIONARIO NUMBER NOT NULL,
                CONSTRAINT MARCACOES_PK PRIMARY KEY (CODIGO_MARCACAO)
);

/*Cria as sequences*/
CREATE SEQUENCE LABDATABASE.MARCACOES_CODIGO_MARCACAO_SEQ;
CREATE SEQUENCE LABDATABASE.FUNCIONARIOS_CODIGO_FUNCIONARIO_SEQ;

/*Cria os relacionamentos*/
ALTER TABLE LABDATABASE.MARCACOES ADD CONSTRAINT FUNCIONARIOS_MARCACOES_FK
FOREIGN KEY (CODIGO_FUNCIONARIO)
REFERENCES LABDATABASE.FUNCIONARIOS (CODIGO_FUNCIONARIO)
NOT DEFERRABLE;

/*Garante acesso total as tabelas*/
GRANT ALL ON LABDATABASE.FUNCIONARIOS TO LABDATABASE;
GRANT ALL ON LABDATABASE.MARCACOES TO LABDATABASE;