INSERT INTO LABDATABASE.FUNCIONARIOS (CODIGO_FUNCIONARIO, NOME, CPF, CARGO)
VALUES (LABDATABASE.FUNCIONARIOS_CODIGO_FUNCIONARIO_SEQ.NEXTVAL, 'João Gomes', '11122233344', 'Analista de Sistemas');

INSERT INTO LABDATABASE.FUNCIONARIOS (CODIGO_FUNCIONARIO, NOME, CPF, CARGO)
VALUES (LABDATABASE.FUNCIONARIOS_CODIGO_FUNCIONARIO_SEQ.NEXTVAL, 'Maria da Penha', '22233344455', 'Desenvolvedora Front-End');

INSERT INTO LABDATABASE.FUNCIONARIOS (CODIGO_FUNCIONARIO, NOME, CPF, CARGO)
VALUES (LABDATABASE.FUNCIONARIOS_CODIGO_FUNCIONARIO_SEQ.NEXTVAL, 'Gustavo Oliveira', '33344455566', 'Gerente de Projetos');

INSERT INTO LABDATABASE.FUNCIONARIOS (CODIGO_FUNCIONARIO, NOME, CPF, CARGO)
VALUES (LABDATABASE.FUNCIONARIOS_CODIGO_FUNCIONARIO_SEQ.NEXTVAL, 'Joana da Silva', '44455566677', 'DevOps Engineer');

INSERT INTO LABDATABASE.FUNCIONARIOS (CODIGO_FUNCIONARIO, NOME, CPF, CARGO)
VALUES (LABDATABASE.FUNCIONARIOS_CODIGO_FUNCIONARIO_SEQ.NEXTVAL, 'Lucas Pereira', '55566677788', 'Desenvolvedor Backend');

INSERT INTO LABDATABASE.FUNCIONARIOS (CODIGO_FUNCIONARIO, NOME, CPF, CARGO)
VALUES (LABDATABASE.FUNCIONARIOS_CODIGO_FUNCIONARIO_SEQ.NEXTVAL, 'Leticia Costa', '66677788899', 'Analista de Qualidade');
