SELECT 
  CODIGO_MARCACAO,
  DATA_MARCACAO,
  TO_CHAR(HORA_ENTRADA, 'HH24:MI') AS HORA_ENTRADA,
  TO_CHAR(HORA_SAIDA, 'HH24:MI') AS HORA_SAIDA,
  CODIGO_FUNCIONARIO
FROM 
  LABDATABASE.MARCACOES
ORDER BY
  CODIGO_FUNCIONARIO, DATA_MARCACAO